/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uaspbo;
import java.sql.*;
import javax.swing.JOptionPane;
import Package2.dataSantri;
import java.util.logging.Level;
import java.util.logging.Logger;
import Package2.dataSantri;
import java.awt.event.KeyEvent;
public class MenuDataSantri extends javax.swing.JFrame {
    dataSantri data_santri;
    /**
     * Creates new form MenuDataSantri
     */
    public MenuDataSantri() throws ClassNotFoundException, SQLException {
        data_santri = new dataSantri();
        initComponents();
        this.showData();
    }
     public boolean checkinput (){
         
         if(txtnamasantri.getText().isEmpty()) return false;
         if(txtorangtua.getText().isEmpty()) return false;
         if(txtjumlahhapalan.getText().isEmpty()) return false;
         
         return true;
         
     }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbsantri = new javax.swing.JTable();
        Kembali = new javax.swing.JButton();
        tambahdata = new javax.swing.JButton();
        update = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnamasantri = new javax.swing.JTextField();
        txtorangtua = new javax.swing.JTextField();
        txtjumlahhapalan = new javax.swing.JTextField();
        txtidsantri = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(164, 195, 162));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Santri");

        tbsantri = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbsantri.getTableHeader().setReorderingAllowed(false);
        tbsantri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Santri", "Nama Santri", "Nama Orang Tua", "Jumlah Hapalan"
            }
        ));
        tbsantri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbsantriMouseClicked(evt);
            }
        });
        tbsantri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbsantriKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(tbsantri);

        Kembali.setBackground(new java.awt.Color(234, 231, 214));
        Kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Kembali.setForeground(new java.awt.Color(93, 123, 111));
        Kembali.setText("Kembali");
        Kembali.setBorderPainted(false);
        Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliMouseClicked(evt);
            }
        });
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        tambahdata.setBackground(new java.awt.Color(234, 231, 214));
        tambahdata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tambahdata.setForeground(new java.awt.Color(93, 123, 111));
        tambahdata.setText("Tambah");
        tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahdataMouseClicked(evt);
            }
        });
        tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahdataActionPerformed(evt);
            }
        });
        tambahdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tambahdataKeyPressed(evt);
            }
        });

        update.setBackground(new java.awt.Color(234, 231, 214));
        update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(102, 102, 255));
        update.setText("Ubah");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(234, 231, 214));
        hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 102, 102));
        hapus.setText("Hapus");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Santri");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Orang Tua ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jumlah Hapalan");

        txtnamasantri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamasantriActionPerformed(evt);
            }
        });
        txtnamasantri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamasantriKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnamasantriKeyTyped(evt);
            }
        });

        txtorangtua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtorangtuaActionPerformed(evt);
            }
        });
        txtorangtua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtorangtuaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtorangtuaKeyTyped(evt);
            }
        });

        txtjumlahhapalan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtjumlahhapalanInputMethodTextChanged(evt);
            }
        });
        txtjumlahhapalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahhapalanActionPerformed(evt);
            }
        });
        txtjumlahhapalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtjumlahhapalanKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjumlahhapalanKeyTyped(evt);
            }
        });

        txtidsantri.setEditable(false);
        txtidsantri.setBackground(new java.awt.Color(164, 195, 162));
        txtidsantri.setForeground(new java.awt.Color(164, 195, 162));
        txtidsantri.setBorder(null);
        txtidsantri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidsantriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtidsantri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtorangtua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                        .addComponent(txtnamasantri, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtjumlahhapalan))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Kembali)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(txtidsantri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamasantri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtorangtua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjumlahhapalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(hapus)
                    .addComponent(tambahdata)
                    .addComponent(Kembali))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 590, 400));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uaspbo/indonesia-hari-santri-nasional-illustration-with-muslim-person-reading-alquran_258153-105__2_-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        
    }//GEN-LAST:event_hapusActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KembaliActionPerformed

    private void tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahdataActionPerformed
        
    }//GEN-LAST:event_tambahdataActionPerformed

    private void tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahdataMouseClicked
        if (checkinput()) {
        String ns = txtnamasantri.getText();
        String ot = txtorangtua.getText();
        String jh = txtjumlahhapalan.getText();
        
//        while (true){
//            if(txtjumlahhapalan.getText().matches("1,2,3,4,5,6,7,8,9,10")){
//                break;
//            }else{
//                JOptionPane.showMessageDialog(null, "Masukkan Input Dengan Benar");
//                this.dispose();
//                try {
//                    new MenuDataSantri().setVisible(true);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (SQLException ex) {
//                    Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
//                }
//             return;
//            }}
        data_santri.insertdataSantri(ns,ot,jh);
        JOptionPane.showMessageDialog(null, "TAMBAH DATA BERHASIL");
        this.dispose();
        try {
            new MenuDataSantri().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
        } 

        
       
        } else {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong");
      
        }
    }//GEN-LAST:event_tambahdataMouseClicked

    private void KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliMouseClicked

        MenuUtama m = new MenuUtama();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KembaliMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        String id = txtidsantri.getText();
        
        data_santri.deleteSantri(id);
        
        JOptionPane.showMessageDialog(null, "Hapus data berhasil");
        this.dispose();
        try {
            new MenuDataSantri().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hapusMouseClicked

    private void tbsantriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbsantriMouseClicked
        
        int baris = tbsantri.rowAtPoint(evt.getPoint());
        String id_santri = tbsantri.getValueAt(baris, 0).toString();
        txtidsantri.setText(id_santri);
        
        String nama_santri = tbsantri.getValueAt(baris, 1).toString();
        txtnamasantri.setText(nama_santri);

        String orangtua_santri = tbsantri.getValueAt(baris, 2).toString();
        txtorangtua.setText(orangtua_santri);

        String jumlahhapalan= tbsantri.getValueAt(baris, 3).toString();
        txtjumlahhapalan.setText(jumlahhapalan);
    }//GEN-LAST:event_tbsantriMouseClicked

    private void txtorangtuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtorangtuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorangtuaActionPerformed

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        if (checkinput()){
            String id = txtidsantri.getText();
            String ns = txtnamasantri.getText();
            String ot = txtorangtua.getText();
            String jh = txtjumlahhapalan.getText();
            
//           while (true){
//            if(txtjumlahhapalan.getText().matches("[0-30]*")){
//                break;
//            }else{
//                JOptionPane.showMessageDialog(null, "Masukkan Input Dengan Benar");
//                this.dispose();
//                try {
//                    new MenuDataSantri().setVisible(true);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (SQLException ex) {
//                    Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                break;
//            }}
            data_santri.updateSantri(ns, ot, jh, id);
            JOptionPane.showMessageDialog(null, "Data berhasil di rubah");
            this.dispose();
            try {
                new MenuDataSantri().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
        }
    }//GEN-LAST:event_updateMouseClicked
    
    void filterangka(KeyEvent b){
        if((Character.isDigit(b.getKeyChar())) && (Character.isJavaIdentifierPart(b.getKeyChar())) ){
            b.consume();
        }
    }
    private void txtjumlahhapalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahhapalanActionPerformed
    while (true){
            if(txtjumlahhapalan.getText().matches("[0-30]*")){
                break;
            }else{
                JOptionPane.showMessageDialog(null, "Masukkan Input Dengan Benar");
                this.dispose();
                try {
                    new MenuDataSantri().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
        }}        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahhapalanActionPerformed

    private void txtjumlahhapalanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtjumlahhapalanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahhapalanInputMethodTextChanged

    private void tbsantriKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbsantriKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tbsantriKeyTyped

    private void txtjumlahhapalanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahhapalanKeyTyped
        char karakter = evt.getKeyChar();
        if(!((karakter >= '0')&& (karakter <= '9')&& txtjumlahhapalan.getText().length()<2 || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtjumlahhapalanKeyTyped

    private void txtorangtuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtorangtuaKeyTyped
        filterangka(evt);
    }//GEN-LAST:event_txtorangtuaKeyTyped

    private void txtnamasantriKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamasantriKeyTyped
        filterangka(evt);
    }//GEN-LAST:event_txtnamasantriKeyTyped

    private void txtnamasantriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamasantriActionPerformed
        while (true){
        if(txtnamasantri.getText().matches("[a-zA-Z]+")){
            break;
        }else{
            JOptionPane.showMessageDialog(null, "Masukkan Input Dengan Benar");
            this.dispose();
            try {
                new MenuDataSantri().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
        }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_txtnamasantriActionPerformed

    private void txtnamasantriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamasantriKeyPressed
    if (evt.getKeyCode()==10){
        while (true){
        if(txtnamasantri.getText().matches("[a-zA-Z]+")){
            txtorangtua.requestFocus();
            break;
        }else{
            JOptionPane.showMessageDialog(null, "Masukkan Input Dengan Benar");
            this.dispose();
            try {
                new MenuDataSantri().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
        }}
    }
    }//GEN-LAST:event_txtnamasantriKeyPressed

    private void tambahdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tambahdataKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahdataKeyPressed

    private void txtorangtuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtorangtuaKeyPressed
    if (evt.getKeyCode()==10){
        while (true){
        if(txtorangtua.getText().matches("[a-zA-Z]+")){
            txtjumlahhapalan.requestFocus();
            break;
        }else{
            JOptionPane.showMessageDialog(null, "Masukkan Input Dengan Benar");
            this.dispose();
            try {
                new MenuDataSantri().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
        }}
    }
    }//GEN-LAST:event_txtorangtuaKeyPressed

    private void txtjumlahhapalanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahhapalanKeyPressed

    }//GEN-LAST:event_txtjumlahhapalanKeyPressed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
 if (checkinput()){
            String id = txtidsantri.getText();
            String ns = txtnamasantri.getText();
            String ot = txtorangtua.getText();
            String jh = txtjumlahhapalan.getText();
           
            data_santri.updateSantri(ns, ot, jh, id);
            JOptionPane.showMessageDialog(null, "Data berhasil di rubah");
            this.dispose();
            try {
                new MenuDataSantri().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void txtidsantriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidsantriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidsantriActionPerformed

    public void showData() throws SQLException {
        tbsantri.setModel(new javax.swing.table.DefaultTableModel(
            data_santri.showSantri(),
            new String [] {
                "ID Santri", "Nama Santri", "Orangtua Santri", "Jumlah Hapalan (Asmaul Husna)"
            }
        ));}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDataSantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDataSantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDataSantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDataSantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuDataSantri().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MenuDataSantri.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembali;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton tambahdata;
    private javax.swing.JTable tbsantri;
    private javax.swing.JTextField txtidsantri;
    private javax.swing.JTextField txtjumlahhapalan;
    private javax.swing.JTextField txtnamasantri;
    private javax.swing.JTextField txtorangtua;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
